---
- name: Provision OpenShift namespace, Artifactory repo, seal secrets, commit to GitHub
  hosts: localhost
  collections:
    - middleware_automation.amq_streams

  tasks:
    - name: Maak topic aan
      kafka_topic:
        name: demo-topic
        partitions: 3
        replicas: 1
        bootstrap_servers: "kafka:9092"
