---
- name: Provision OpenShift namespace, Artifactory repo, seal secrets, commit to GitHub
  hosts: localhost
  collections:
    - middleware_automation.amq_streams

  tasks:
    - name: Stuur bericht naar topic
      kafka_producer:
        topic: it4it.automation_gateway.action.response
        bootstrap_servers: "kafka.aa062759-dev.svc.cluster.local:9092"
        value: '{"bericht": "Hallo via Ansible Collection!"}'
